version: '3'
services:
  proxy:
    image: traefik
    restart: unless-stopped
    command: --web --docker --docker.exposedByDefault=false --loglevel=info
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - ./traefik/traefik.toml:/traefik.toml
     - ./traefik/cert:/ssl:ro
    ports:
     - "80:80"
     - "443:443"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    expose:
     - "9200"
     - "9300"
    environment:
     - cluster.name=elasticsearch
     - xpack.security.enabled=false
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    restart: always
    ports:
     - "5601:5601"
  rc:
    image: sixsq/ring-container:3.52
    expose:
     - "5000"
    volumes:
     - ringcontainer:/opt/slipstream/ring-container
     - ringcontainerexample:/opt/slipstream/ring-example
    command: sh
  cimi:
    image: mf2c/cimi-server:2.19-SNAPSHOT
    depends_on:
      - elasticsearch
    expose:
     - "8201"
    labels:
     - "traefik.enable=true"
     - "traefik.backend=cimi"
     - "traefik.frontend.rule=PathPrefix:/,/"
    volumes:
     - ringcontainer:/opt/slipstream/ring-container
     - ringcontainerexample:/opt/slipstream/ring-example
  rc:
    image: sixsq/ring-container:3.52
    expose:
     - "5000"
    volumes:
     - ringcontainer:/opt/slipstream/ring-container
     - ringcontainerexample:/opt/slipstream/ring-example
    command: sh
  eventService:
    image: sixsq/cimi-sse:1.0.1
    depends_on:
      - cimi
    ports:
      - "8000:8000"
      - "8001:8001"
    restart: unless-stopped
  service-manager:
    image: mf2c/service-manager:latest
    restart: unless-stopped
    depends_on:
      - cimi
    expose:
      - 46200
    ports:
      - 46200:46200
    environment:
      - JAVA_OPTS=-Xms32m -Xmx256m

volumes:
  ringcontainer: {}
  ringcontainerexample: {}
